### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by zoufolin** [zoufolin/blog#1]
# CSS Modules

本文示例代码为 `React + CSS Modules`，使用 `Create-React-App` CLI 生成的项目。

## 一、Why

1. 减少冲突
2. 明确依赖
3. 减少全局作用

使 CSS 变得模块化和可复用，且 CSS Modules 易学、规则少，同时保证样式都变成组件独立样式，从而不会影响到其他组件。

---

### 2.1 局部作用域

局部作用域就是唯一的，会生成独一无二的 classname，使用 `:local(.className)` 或者 `.className`方式定义局部作用域的 classname。

```js
// App.js

import React from 'react';
import styles from './App.module.css';
// import { title } from './App.module.css';   也支持这样导入

export default () => {
  return <h1 className={styles.title}>Hello World</h1>;
};
```

[Create-React-App 文档](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet) 推荐 `[name].module.css` 规则来命名 CSS 文件。

```css
/* App.module.css */

.title {
  color: red;
}

/* 或者 */

:local(.title) {
  color: red;
}
```

构建工具会把 styles.title 编译成唯一的 classname，项目会按照 `[filename]_[classname]__[hash]` 规则生成 classname，且只对该组件有效。

```html
<h1 class="App_title__6RUa2">Hello World</h1>
```

### 2.2 全局作用域

`CSS Modules`允许使用 `:global(.className)` 方式来定义全局作用域的 classname，这种定义不会编译成哈希字符串，从而声明一个全局规则。

```js
// App.js

import React from 'react';
import styles from './App.module.css';

export default () => {
  return <h1 className="title">Hello World</h1>;
};
```

```css
/* App.module.css */

.title {
  color: red;
}

:global(.title) {
  color: green;
}
```

---

## 三、命名

[CSS Modules 文档](https://github.com/css-modules/css-modules) 推荐使用 `camelCase 驼峰式命名法`，但不是强制性。  
同样也可以使用 `kebab-case 短横线式命名法`，只是使用该命名法是，在 JavaScript 代码中就不能这样 `styles.className` 使用，这时要使用 `styles['class-name']`。

---

## 四、 基于 Webpack 使用

在 `css-loader` 后面加上查询参数 `modules`，表示使用 `CSS Modules` 功能。

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true
            }
          }
        ]
      }
    ]
  }
};
```

也可以`定制`编译后的`类名命名规则`。

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[hash:base64:6]'
            }
          }
        ]
      }
    ]
  }
};
```

---

### 5.1 同文件内继承

一个选择器可以继承另一个选择器的规则，这称为"组合"。

```css
/* App.module.css */

.className {
  color: green;
  background: red;
}

.otherClassName {
  composes: className;
  color: yellow;
}
```

```js
// App.js

import React from 'react';
import styles from './App.module.css';

export default () => {
  return <h1 className={styles.otherClassName}>Hello World</h1>;
};
```

编译后，`h1` 的 `classname`：

```html
<h1 class="App_className__Ijf8a App_otherClassName__buq6a2">Hello World</h1>
```

### 5.2 依赖其他 CSS 模块

选择器也可以继承其他 CSS 文件里面的规则。

```css
/* className.module.css */
.className {
  color: green;
  background: red;
}

/* otherClassName.module.css */
.otherClassName {
  composes: className from './className.module.css';
  color: yellow;
}
```

### 5.3 依赖全局的 CSS 模块

选择器也可以继承全局的 CSS 规则。

```css
.otherClassName {
  composes: globalClassName from global;
}
```

---

## 六、变量

CSS Modules 支持使用`变量`，不过需要安装 `PostCSS` 和 `postcss-modules-values`。

```js
npm i -S postcss-loader postcss-modules-values
```

Webpack 配置文件：

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true
            }
          },
          'postcss-loader'
        ]
      }
    ]
  }
};
```

定义变量：

```css
/* colors.css */

@value blue: #0c77f8;
@value red: #ff0000;
@value green: #aaf200;
```

引用定义变量：

```css
/* App.css */

@value colors: "./colors.css";
@value blue, red, green from colors;

.title {
  color: red;
  background-color: blue;
}
```
